databases:
  - name: inventory_system
    databaseName: inventory_system
    user: inventory_system
    plan: free

services:
  - type: web
    name: inventory_system
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory_system
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
